 import React from 'react';
import '../Home/Home';
 
 function ScrollContainer() {
   return (
     <div style={{height:400, overflow:'auto' , border:'1px solid white',padding:30,backgroundColor:'purple',color:'white'}}>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus molestias magni atque nostrum dolorem et repellat beatae ipsam illo quisquam.</p>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ex magni reprehenderit soluta? Nesciunt odio porro ex unde corporis odit tempore eius dicta quas ea suscipit, pariatur obcaecati, maxime dolore, maiores ipsum illum blanditiis cumque. Nostrum placeat quam, nemo, neque velit itaque expedita, molestias illum unde aliquam consequuntur! Quisquam dicta ipsa dolore consequatur reprehenderit vero quibusdam! Porro eveniet dolorum vel quo corporis labore! Distinctio voluptatum necessitatibus reprehenderit aspernatur? Mollitia ab autem doloremque a sint beatae culpa porro fuga, veritatis quasi laudantium praesentium voluptatibus exercitationem veniam aliquid nulla placeat incidunt harum ad ipsa dolores quis, aliquam totam. Incidunt molestiae harum accusantium odio, neque culpa fugit, eos voluptatum ipsum dicta beatae quam similique voluptates? Officia vitae error perferendis consectetur aliquam? Eaque dignissimos at nostrum velit excepturi aut eum commodi, odio voluptatum sed. Voluptatibus minima reprehenderit dicta, explicabo, amet dolor repellendus accusantium adipisci officiis impedit quos iure delectus cum possimus. Iure maxime est animi. Expedita voluptatem praesentium nihil quae ab neque incidunt hic quia officia perferendis sed labore, ipsam saepe aut minima enim nobis possimus. Voluptatem dicta, quasi, quia est vel, recusandae accusantium eveniet deleniti molestias perspiciatis animi laudantium voluptatibus praesentium. Inventore illum ipsum labore tempora laudantium ullam et veniam dolorum obcaecati quo.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit praesentium maiores molestiae maxime iste, inventore suscipit sed iusto ducimus rerum corporis tempora illo! Impedit vero iure placeat dignissimos quidem debitis rerum, nemo aspernatur, labore dolore aliquam repellat blanditiis, et accusantium totam incidunt asperiores porro magni voluptates consequatur earum unde odio aut! Doloribus, sit nisi dolorum deleniti incidunt quas ab odio ex nobis quasi exercitationem ducimus vel? Quos veritatis corporis dolore eligendi qui numquam similique voluptate voluptatum, laborum optio molestiae eius est tenetur ullam quasi magnam eum hic corrupti. Inventore consequuntur nobis beatae fugit quas ut aut eligendi reprehenderit omnis dicta dignissimos doloremque corrupti optio, quo dolorem veritatis a? Aut natus aperiam repellat expedita architecto? Aut harum temporibus, sit reprehenderit praesentium excepturi obcaecati ratione consequatur pariatur debitis doloribus ipsum recusandae, illum itaque reiciendis esse suscipit magnam voluptatem rem cumque quae eveniet aliquid nobis. Iure incidunt amet labore ab ipsam nemo. Sapiente ducimus, maiores sit necessitatibus labore quod sequi ipsa suscipit dicta expedita quas temporibus ad quibusdam et exercitationem numquam facere est! Fuga temporibus mollitia magnam! Sit odio rem eveniet necessitatibus ipsam ratione, amet porro cumque itaque dicta consequuntur tempora autem, eum tempore quod minima perspiciatis omnis quisquam eligendi atque quidem dolores? Quod laborum illo vel officiis nihil inventore voluptates et voluptas modi aspernatur in tempora, perspiciatis necessitatibus minus quis vitae dolores quos accusamus doloremque dignissimos facere accusantium distinctio ad. Illum ipsum, error optio doloribus dolorum cum! Quis sed reiciendis autem ipsa nemo, ex, asperiores omnis quod perferendis fugit distinctio facilis! Deserunt blanditiis suscipit sapiente perferendis repellat consequatur possimus veritatis totam debitis. Odit nam id veniam illo. Quis, eligendi quaerat deserunt harum earum maiores fugit aperiam ad id nam mollitia fugiat, facilis nostrum voluptatem amet et in! Odit, dignissimos nobis ab facilis repellat quis ducimus, tempore pariatur laudantium dolor perspiciatis tenetur eius?</p>

     </div>
   )
 }
 
 export default ScrollContainer